import type { Article, Block } from "./types";

const shared = {
  author: "Epoch Research Desk",
  authorRole: "Epoch Olympiad Foundation",
} as const;

function article(
  slug: string,
  title: string,
  subtitle: string,
  category: string,
  date: string,
  image: string,
  tags: string[],
  blocks: Block[]
): Article {
  return { slug, title, subtitle, category, date, image, tags, blocks, ...shared };
}

export const newArticles: Article[] = [
  article(
    "the-future-of-international-assessments",
    "The Future of International Assessments",
    "From measuring answers to understanding how learners think.",
    "Future of Assessment",
    "2026-08-23",
    "/images/article-3.png",
    ["assessment", "future learning", "reasoning"],
    [
      { kind: "lead", text: "International assessments have traditionally helped compare academic performance across students, schools and countries. But the needs of today's learners are changing. A future-ready assessment should ask not only what a child answered correctly, but how the child thought, reasoned, applied and solved." },
      { kind: "takeaways", title: "In short", items: ["Assessment is evolving beyond the measurement of memory.", "Understanding, reasoning, application and problem-solving deserve visibility.", "A learner profile is more useful than a single score.", "The future of assessment is about asking better questions."] },
      { kind: "heading", text: "Assessment is evolving" },
      { kind: "paragraph", text: "The purpose of assessment is gradually moving beyond simply measuring how much information a learner can remember. A more meaningful assessment looks at understanding, reasoning, application, problem-solving and analytical thinking. The goal is not to replace academic assessment, but to make it more meaningful." },
      { kind: "heading", text: "What should future assessments measure?" },
      { kind: "checklist", title: "Six dimensions of future-ready learning", items: ["Understanding — can the learner make sense of a concept?", "Reasoning — can the learner connect information and reach a conclusion?", "Application — can the learner use knowledge in a new situation?", "Problem-solving — can the learner approach an unfamiliar problem?", "Analytical thinking — can the learner examine information before deciding?", "Learning readiness — what does the current profile suggest about future development?"] },
      { kind: "heading", text: "From one score to a learner profile" },
      { kind: "compare", title: "Two ways to see an assessment", columns: ["Traditional assessment", "Future-ready assessment"], rows: [{ label: "The journey", left: "Question → Answer → Marks", right: "Question → Thinking → Understanding → Application → Insight" }, { label: "What it provides", left: "A snapshot of performance", right: "A deeper understanding of how a child approaches learning" }] },
      { kind: "heading", text: "International competition, deeper understanding" },
      { kind: "paragraph", text: "International Olympiads can do more than identify students who perform exceptionally well. They can encourage learners to think beyond familiar questions, apply concepts in unfamiliar situations, reason before reaching an answer, solve problems independently and develop confidence in their own thinking. International assessment can become a tool for learning—not merely ranking." },
      { kind: "quote", text: "The future of assessment is not about asking more questions. It is about asking better questions." },
      { kind: "heading", text: "The Epoch perspective" },
      { kind: "paragraph", text: "At Epoch Olympiad Foundation, we envision international assessments that provide meaningful insights into how children understand, reason, apply and learn. That is why our approach looks beyond marks and towards deeper academic insight." },
      { kind: "faq", title: "Questions parents ask", items: [{ q: "Are future-ready assessments replacing academic assessment?", a: "No. They complement academic assessment by making understanding, reasoning, application and problem-solving more visible." }, { q: "Why is a learner profile useful?", a: "A profile shows how a child approaches learning, so parents and educators can recognise strengths and provide more targeted support." }] },
    ]
  ),
  article(
    "balanced-diet-for-the-brain",
    "Balanced Diet for the Brain",
    "Why children need more than one kind of learning.",
    "Holistic Learning",
    "2026-08-22",
    "/images/article-4.png",
    ["IHOST", "holistic learning", "thinking skills"],
    [
      { kind: "lead", text: "Just as the body needs a balanced diet to grow well, the brain needs a balanced learning experience to develop different ways of thinking. A child may be good at Mathematics but struggle to explain a scientific idea, or know many facts but find an unfamiliar problem difficult." },
      { kind: "heading", text: "Four essential ingredients for a thinking mind" },
      { kind: "steps", items: [{ title: "Mathematics — building logical thinking", text: "Mathematics helps children recognise patterns, understand relationships, analyse information and arrive at logical solutions." }, { title: "Science — understanding how things work", text: "Science encourages children to observe, question, explore and understand the world around them." }, { title: "Aptitude — applying thinking to new situations", text: "Aptitude develops reasoning, judgement and problem-solving when children encounter unfamiliar situations." }, { title: "General Knowledge — connecting with the world", text: "General Knowledge expands awareness and helps the brain connect learning with real life." }] },
      { kind: "compare", title: "A balanced diet for the brain", columns: ["The ingredient", "What it develops"], rows: [{ label: "Mathematics", left: "Structure", right: "Logical thinking" }, { label: "Science", left: "Curiosity", right: "Observation and explanation" }, { label: "Aptitude", left: "Application", right: "Reasoning in new situations" }, { label: "General Knowledge", left: "Awareness", right: "Connections with the world" }] },
      { kind: "heading", text: "Introducing IHOST" },
      { kind: "paragraph", text: "International Holistic Olympiad for Smart Thinkers brings Mathematics, Science, Aptitude and General Knowledge together in one holistic learning experience. Rather than treating subjects as isolated areas, IHOST encourages children to think logically, explore with curiosity, apply knowledge, connect ideas and approach unfamiliar problems with confidence." },
      { kind: "quote", text: "One brain. Four dimensions. A more balanced way to learn." },
      { kind: "heading", text: "From subject learning to holistic thinking" },
      { kind: "paragraph", text: "The future belongs not only to children who can remember information, but to those who can understand it, connect it, question it and use it. A balanced learning approach gives every child more opportunities to discover how to think—not just what to learn." },
      { kind: "callout", tone: "tip", title: "Explore IHOST", text: "Think • Explore • Discover • Excel" },
    ]
  ),
  article(
    "how-kindergarten-cognitive-assessment-works",
    "How Kindergarten Cognitive Assessment Works",
    "Understanding how a young child thinks—not just what they know.",
    "Early Learning",
    "2026-08-21",
    "/images/article-6.png",
    ["kindergarten", "cognitive assessment", "Brainiac Global"],
    [
      { kind: "lead", text: "Kindergarten is a critical stage when children begin developing the foundations of observation, curiosity, reasoning, problem-solving and learning readiness. A meaningful cognitive assessment should be age-appropriate, engaging and focused on understanding a child's thinking—not putting academic pressure on them." },
      { kind: "heading", text: "From observation to insight" },
      { kind: "steps", items: [{ title: "Observe", text: "Children notice differences, recognise patterns and explore possibilities through simple, engaging situations." }, { title: "Think", text: "The assessment observes how a child approaches a question, rather than testing how much they have memorised." }, { title: "Reason", text: "Children connect information, make choices, identify relationships and use simple reasoning." }, { title: "Solve", text: "Age-appropriate challenges reveal how a child approaches simple problems and unfamiliar situations." }, { title: "Understand", text: "Responses are brought together into meaningful insights about thinking abilities and learning readiness." }] },
      { kind: "heading", text: "What does the assessment tell parents?" },
      { kind: "checklist", items: ["Observation", "Pattern recognition", "Reasoning", "Problem-solving", "Thinking and application", "Learning readiness"] },
      { kind: "callout", tone: "caution", title: "The purpose", text: "The objective is not to label a child. It is to understand the child better." },
      { kind: "heading", text: "From early thinking to meaningful insight" },
      { kind: "paragraph", text: "Brainiac Global brings age-appropriate cognitive assessment to the early years through engaging experiences designed to nurture curiosity, observation, reasoning and foundational thinking. Its International Brain Booster Olympiad makes assessment enjoyable and motivating while providing parent-friendly insight." },
      { kind: "heading", text: "Assessment gives a picture. Everyday learning shows the journey." },
      { kind: "paragraph", text: "MY CCBee complements structured assessment by helping schools and parents follow daily activities and performance: what happened, how the child performed and where support may be needed." },
      { kind: "quote", text: "Understand early. Support better. Help every child grow." },
    ]
  ),
  article(
    "importance-of-academic-health-report",
    "Importance of the Academic Health Report",
    "Beyond marks. Understand how a child learns.",
    "Academic Health",
    "2026-08-20",
    "/images/article-5.png",
    ["academic health", "assessment", "learning insight"],
    [
      { kind: "lead", text: "Marks tell us how a child performed in a particular assessment. But they do not always tell us how the child thinks, understands, reasons, applies knowledge or approaches a problem. An Academic Health Report brings these aspects together for a clearer picture of academic and cognitive development." },
      { kind: "heading", text: "What does an Academic Health Report help you understand?" },
      { kind: "checklist", items: ["Conceptual understanding — does the child understand ideas or mainly remember them?", "Reasoning and problem-solving — can the child think through a situation?", "Analytical thinking — can the child examine information and make connections?", "Application — can the child use learning in different situations?", "Learning readiness and development — what does the current profile suggest?"] },
      { kind: "heading", text: "Why it matters at different stages" },
      { kind: "compare", title: "One journey, different stages", columns: ["Initiative", "Focus"], rows: [{ label: "Brainiac Global", left: "Understanding the foundations", right: "Observation, pattern recognition, reasoning, problem-solving and readiness" }, { label: "Epoch Olympiad", left: "Understanding growing intelligence", right: "Conceptual understanding, analytical reasoning, scientific thinking and application" }, { label: "MY CCBee", left: "Continuous everyday insight", right: "Activities, performance, analytics and timely intervention" }] },
      { kind: "heading", text: "From marks to meaning" },
      { kind: "paragraph", text: "An Academic Health Report should not replace marks. It should add meaning to them. Knowing what a child scored is useful. Knowing how a child is learning is far more powerful." },
      { kind: "faq", title: "Questions parents ask", items: [{ q: "Does an Academic Health Report replace a report card?", a: "No. It complements academic results by showing meaningful dimensions behind performance." }, { q: "Who can use the report?", a: "Parents and educators can use it to understand strengths, areas for growth and possible next steps." }] },
    ]
  ),
  article(
    "what-is-competency-based-assessment",
    "What Is Competency-Based Assessment?",
    "A simple guide for parents—from what a child remembers to what a child can do with learning.",
    "Assessment",
    "2026-08-19",
    "/images/article-7.jpg",
    ["competency", "assessment", "application"],
    [
      { kind: "lead", text: "A child may remember a formula, definition or fact and still struggle to use it in a new situation. Competency-based assessment focuses on whether a child can understand, apply, reason, connect ideas and solve problems—not simply reproduce information." },
      { kind: "heading", text: "What does competency mean?" },
      { kind: "paragraph", text: "In simple words, a competency is the ability to use knowledge and skills effectively in a situation. A child may remember that 5 × 4 = 20, but can the child use multiplication to solve a real-life problem? Knowledge tells us what a child knows. Competency shows us what a child can do with it." },
      { kind: "compare", title: "Traditional and competency-based assessment", columns: ["Traditional focus", "Competency-based focus"], rows: [{ label: "Question", left: "What did the child remember?", right: "What does the child understand?" }, { label: "Learning", left: "Can the child reproduce the answer?", right: "Can the child apply the idea?" }, { label: "Challenge", left: "Can the child solve familiar questions?", right: "Can the child handle a new situation?" }, { label: "Result", left: "What marks did the child receive?", right: "What abilities did the child demonstrate?" }] },
      { kind: "heading", text: "What can competency-based assessment look at?" },
      { kind: "checklist", items: ["Conceptual understanding", "Reasoning", "Problem-solving", "Application", "Analytical thinking", "Learning readiness"] },
      { kind: "heading", text: "From early thinking to growing intelligence" },
      { kind: "paragraph", text: "Brainiac Global develops foundational abilities for kindergarten learners through joyful, age-appropriate experiences. Epoch Olympiad explores conceptual understanding, analytical reasoning, scientific thinking, problem-solving and knowledge application for school-age learners. Both reflect the same belief: assessment should reveal how children think—not merely what they remember." },
      { kind: "quote", text: "Remember → Understand → Apply → Reason → Solve. That is the journey from knowledge to competency." },
    ]
  ),
  article(
    "what-is-critical-thinking",
    "What Is Critical Thinking? How Children Learn to Think Beyond the Obvious",
    "Critical thinking is not about knowing more answers. It is about learning to think carefully before accepting an answer.",
    "Thinking Skills",
    "2026-08-18",
    "/images/article-8.jpg",
    ["critical thinking", "parents", "thinking skills"],
    [
      { kind: "lead", text: "When children develop critical thinking, they learn to observe, question, compare, connect information, look for reasons and make thoughtful decisions instead of simply choosing the first answer that appears obvious." },
      { kind: "heading", text: "What does thinking beyond the obvious mean?" },
      { kind: "paragraph", text: "Ask which object will sink in water. One child may recall a textbook answer. Another may ask what the object is made of, how heavy it is and whether its shape matters. One is recalling information; the other is using information to reason. Critical thinking begins when children ask “Why?” and “How?”" },
      { kind: "heading", text: "Five simple signs of critical thinking" },
      { kind: "steps", items: [{ title: "Observe carefully", text: "Notice details instead of rushing to an answer." }, { title: "Ask questions", text: "Want to understand why something happens." }, { title: "Compare and connect", text: "Identify similarities, differences, patterns and relationships." }, { title: "Consider possibilities", text: "Understand that the first answer is not always the only answer." }, { title: "Explain thinking", text: "Tell you why an answer was chosen, not just what it is." }] },
      { kind: "heading", text: "How can parents encourage it?" },
      { kind: "checklist", items: ["What do you think?", "Why do you think that?", "What else could happen?", "How can we find out?", "Can you think of another way?"] },
      { kind: "heading", text: "The bigger picture" },
      { kind: "paragraph", text: "Critical thinking is a foundation for lifelong learning, not a separate subject for an examination. Brainiac Global builds early foundations; Epoch Olympiad explores conceptual understanding and application; MY CCBee helps schools track everyday learning so insight can lead to timely action." },
      { kind: "quote", text: "Don't just teach children what to think. Help them develop the habit of thinking." },
    ]
  ),
  article(
    "identify-learning-gaps-before-problems",
    "How to Identify Learning Gaps Before They Become Learning Problems",
    "A learning gap is not failure. It is an area where a child may need more support, practice or a different way of learning.",
    "Learning Support",
    "2026-08-17",
    "/images/article-9.jpg",
    ["learning gaps", "early support", "parents"],
    [
      { kind: "lead", text: "A child may be getting good marks and still have a learning gap. A child may remember a mathematical formula but struggle to use it in a new situation, or read fluently but find it difficult to explain what they understood. The earlier gaps are noticed, the easier it is to support the child." },
      { kind: "heading", text: "What is a learning gap?" },
      { kind: "paragraph", text: "A learning gap is the difference between what a child is expected to understand or do and what the child can currently demonstrate. It may appear in conceptual understanding, logical reasoning, problem-solving, comprehension, application, observation or subject-specific skills." },
      { kind: "heading", text: "Five early signs parents can notice" },
      { kind: "steps", items: [{ title: "Remembers but cannot explain", text: "The child gives an answer but struggles to explain why it is correct." }, { title: "Familiar is easy, new is difficult", text: "The child struggles when the same idea is presented differently." }, { title: "The same mistake returns", text: "Repeated errors may indicate that an underlying concept needs attention." }, { title: "Avoids certain activities", text: "Consistent difficulty with reading, mathematics, reasoning or problem-solving is worth exploring." }, { title: "One area stays behind", text: "Overall performance may look satisfactory while one skill needs support." }] },
      { kind: "callout", tone: "note", title: "Look for patterns", text: "One sign alone does not prove a learning gap. Patterns over time are more meaningful." },
      { kind: "heading", text: "From finding a gap to taking action" },
      { kind: "steps", title: "A useful cycle", items: [{ title: "Assess", text: "Look at understanding, reasoning, application and problem-solving—not only memory." }, { title: "Compare", text: "Use appropriate benchmarks to see where progress is strong and where support may help." }, { title: "Track", text: "Observe performance over time to distinguish a temporary difficulty from a continuing one." }, { title: "Act", text: "Provide targeted practice, explanation or additional learning opportunities." }] },
      { kind: "paragraph", text: "An Academic Health Report can bring different aspects of learning into one understandable picture. Brainiac Global, Epoch Olympiad and MY CCBee support a simple principle: don't wait for a learning problem to become visible. Look for the learning gap early." },
    ]
  ),
  article(
    "does-your-child-understand-or-memorise",
    "Does Your Child Understand or Just Memorise? 5 Simple Signs",
    "A simple guide for parents.",
    "Parent Guide",
    "2026-08-16",
    "/images/article-10.jpg",
    ["understanding", "memorisation", "parent guide"],
    [
      { kind: "lead", text: "A child can remember an answer without truly understanding the idea behind it. They may score well on familiar questions but become confused when the question changes. This does not mean the child is weak—it raises an important question: is your child learning to remember, or learning to understand?" },
      { kind: "heading", text: "Five signs of understanding" },
      { kind: "steps", items: [{ title: "Can your child explain the answer?", text: "Ask why it is correct. Understanding usually appears as reasoning in the child's own words." }, { title: "Can your child use the idea in a new situation?", text: "Change the question slightly. Real learning becomes useful when the situation changes." }, { title: "Does your child ask why and how?", text: "Questions show that the child is trying to connect ideas rather than collect answers." }, { title: "Can your child spot a mistake?", text: "Identifying an error and explaining why it is wrong is a foundation for independent reasoning." }, { title: "Does learning stay after the question changes?", text: "Understanding is flexible when wording, examples or combinations change." }] },
      { kind: "heading", text: "Understanding is more than marks" },
      { kind: "checklist", items: ["Conceptual understanding", "Reasoning", "Application", "Problem-solving", "Observation", "Decision-making"] },
      { kind: "heading", text: "The simple parent test" },
      { kind: "paragraph", text: "The next time your child gives you the correct answer, don't stop at “Correct!” Try asking: “How did you get this answer?” That one question can tell you much more about learning than the answer alone." },
      { kind: "quote", text: "Don't just ask what your child knows. Ask how your child thinks." },
    ]
  ),
  article(
    "seven-skills-children-need-for-the-future",
    "Beyond Marks: 7 Skills Children Need for the Future",
    "Good marks can open doors. The future will ask children to do much more than remember information.",
    "Future Readiness",
    "2026-08-15",
    "/images/article-11.jpg",
    ["future skills", "parents", "holistic learning"],
    [
      { kind: "lead", text: "Children will need to think, question, solve problems, adapt to change, communicate ideas and make thoughtful decisions. This does not make academic learning less important. It means children need to learn how to use what they know." },
      { kind: "heading", text: "Seven skills children need" },
      { kind: "steps", items: [{ title: "Critical thinking", text: "Look beyond the obvious and question assumptions." }, { title: "Problem-solving", text: "Understand a problem, explore possibilities, try a solution and learn from the result." }, { title: "Reasoning and decision-making", text: "Compare possibilities, identify patterns and understand consequences." }, { title: "Curiosity and questioning", text: "Explore why, how and what if." }, { title: "Communication", text: "Explain ideas and reasoning clearly, listen to others and communicate with confidence." }, { title: "Adaptability and application", text: "Use existing knowledge in new situations and adapt when circumstances change." }, { title: "Digital and future literacy", text: "Navigate technology, information, financial understanding and responsible decision-making thoughtfully." }] },
      { kind: "heading", text: "These skills do not develop in one day" },
      { kind: "paragraph", text: "They develop through everyday experiences, meaningful questions, practice, reflection, assessment and timely support. That is why education needs opportunities to observe how children think, learn, apply and grow." },
      { kind: "compare", title: "A fuller definition of progress", columns: ["Not just", "Also"], rows: [{ label: "Achievement", left: "Marks", right: "Understanding and application" }, { label: "Learning", left: "Remembering", right: "Thinking and adapting" }, { label: "Success", left: "One result", right: "Continued growth" }] },
      { kind: "quote", text: "Marks + Understanding + Skills: that is the foundation of future readiness." },
    ]
  ),
  article(
    "why-early-childhood-build-thinking-skills",
    "Why Early Childhood Is the Right Time to Build Thinking Skills",
    "A simple guide for parents.",
    "Early Learning",
    "2026-08-14",
    "/images/article-12.jpg",
    ["early childhood", "Brainiac Global", "thinking skills"],
    [
      { kind: "lead", text: "Before children solve equations, write essays or prepare for examinations, they are already learning how to observe, question, connect and make sense of the world. The early years are not just preparation for school; they are the foundation for how a child learns." },
      { kind: "heading", text: "Thinking skills begin before formal learning" },
      { kind: "paragraph", text: "When a child notices differences, recognises a pattern, predicts what might happen, tries another way after a mistake or asks why something works, the child is doing more than playing. They are beginning to think." },
      { kind: "heading", text: "Five thinking foundations children can develop early" },
      { kind: "steps", items: [{ title: "Observation", text: "Notice details, differences, similarities, changes and relationships." }, { title: "Curiosity", text: "Ask why and how, becoming an active learner." }, { title: "Pattern recognition", text: "Recognise patterns in shapes, colours, numbers, sounds and routines." }, { title: "Reasoning", text: "Connect observations with conclusions." }, { title: "Problem-solving", text: "Try different ways and learn that a problem can have more than one approach." }] },
      { kind: "callout", tone: "caution", title: "Thinking is not the same as early academics", text: "The goal is not how much a child can memorise. It is how the child observes, understands, explores and responds." },
      { kind: "heading", text: "Why start early?" },
      { kind: "paragraph", text: "Early childhood gives children countless opportunities to develop thinking naturally: Observe → Explore → Question → Connect → Reason → Solve. These foundations grow alongside academic learning from kindergarten onwards." },
      { kind: "quote", text: "Develop a habit of how to think, not what to think." },
    ]
  ),
  article(
    "why-olympiad-exams-should-be-more-than-competition",
    "Why Olympiad Exams Should Be More Than Competition",
    "A simple guide for parents.",
    "Olympiad Learning",
    "2026-08-13",
    "/images/article-13.jpg",
    ["Olympiad", "competition", "learning insight"],
    [
      { kind: "lead", text: "Rankings, medals and certificates are exciting parts of an Olympiad journey. But an Olympiad can offer something more valuable: an opportunity to discover how a child thinks, understands and applies what they have learned. Competition can motivate children, but learning should be the bigger purpose." },
      { kind: "heading", text: "What should a good Olympiad do?" },
      { kind: "checklist", items: ["Assess understanding, not just recall.", "Offer opportunities for application in unfamiliar situations.", "Encourage reasoning before reaching an answer.", "Present challenges that require problem-solving.", "Provide useful insight into a child's learning."] },
      { kind: "heading", text: "Competition has a place—but it should not be the whole story" },
      { kind: "paragraph", text: "Awards and recognition can motivate children, but children should not believe that winning is the only purpose of learning. The better message is: compete with curiosity, learn from the challenge and celebrate progress." },
      { kind: "heading", text: "From competition to discovery" },
      { kind: "compare", title: "A better way to read results", columns: ["Traditional result", "Meaningful insight"], rows: [{ label: "Two children", left: "Child A — 82 marks; Child B — 82 marks", right: "One may need application practice; another may need subject support." }, { label: "The score", left: "A final ranking", right: "A starting point for understanding" }] },
      { kind: "heading", text: "Assessment meets learning" },
      { kind: "paragraph", text: "Brainiac Global discovers thinking early. Epoch Olympiad assesses, challenges and recognises learners from Classes 1–10. MY CCBee keeps everyday learning visible, while the Academic Health Report turns results into insight." },
      { kind: "quote", text: "Competition can create excitement. Learning creates lasting value." },
      { kind: "faq", title: "Questions parents ask", items: [{ q: "Are Olympiad exams only about competition?", a: "No. Competition can motivate, while an effective Olympiad also develops understanding, reasoning, application and problem-solving." }, { q: "Should parents focus only on rank?", a: "Rank is one indicator. Parents can gain more value from what performance reveals about strengths and areas for growth." }, { q: "What makes an Olympiad meaningful?", a: "Appropriate assessment, useful feedback, learning opportunities, challenge and recognition of effort and achievement." }] },
    ]
  ),
  article(
    "how-to-choose-the-right-olympiad",
    "How to Choose the Right Olympiad for Your Child",
    "The right choice begins with understanding what your child needs to learn, practise or discover.",
    "Parent Guide",
    "2026-08-12",
    "/images/article-14.jpg",
    ["Olympiad", "parent guide", "learning"],
    [
      { kind: "lead", text: "Parents can choose from Olympiads covering Mathematics, Science, General Knowledge, Aptitude and more. The answer should not depend only on popularity, prizes or participation. A good choice begins with understanding what your child needs right now." },
      { kind: "heading", text: "Five questions to ask before choosing" },
      { kind: "steps", items: [{ title: "What does it assess?", text: "Look for conceptual understanding, reasoning, problem-solving and application—not only factual recall." }, { title: "Is it age-appropriate?", text: "The right level should stretch a child without creating unnecessary stress." }, { title: "Does it offer competition or learning?", text: "Ideally, the experience provides both challenge and meaningful learning." }, { title: "What happens after the examination?", text: "Look for performance information, benchmarks, feedback and further learning opportunities." }, { title: "Does it encourage future-ready skills?", text: "Critical thinking, reasoning, problem-solving, application, curiosity and decision-making matter." }] },
      { kind: "heading", text: "Which type may suit your child?" },
      { kind: "compare", title: "Match the experience to the need", columns: ["Your child's need", "Look for"], rows: [{ label: "Mathematics interest", left: "Strong interest in Mathematics", right: "Conceptual and problem-solving questions" }, { label: "Science interest", left: "Interest in Science", right: "Understanding and application" }, { label: "Reasoning development", left: "Developing reasoning skills", right: "Aptitude and reasoning assessment" }, { label: "Balanced development", left: "Multiple areas", right: "A holistic learning experience" }, { label: "Early development", left: "Kindergarten learner", right: "Age-appropriate cognitive experiences" }] },
      { kind: "heading", text: "Don't choose an Olympiad only for the trophy" },
      { kind: "paragraph", text: "Before registering, ask: will this Olympiad help my child understand more, think, reveal something useful about learning and become more curious? The right Olympiad is not necessarily the one with the biggest competition. It is the one with the right learning challenge." },
      { kind: "checklist", title: "A simple parent checklist", items: ["Age and class suitability", "Subject or skill assessed", "Assessment pattern", "Understanding versus memorisation", "Reasoning and application", "Feedback and performance insights", "Learning opportunities after assessment", "Child-friendly experience"] },
      { kind: "quote", text: "Choose an Olympiad for the learning. Let recognition follow the achievement." },
    ]
  ),
  article(
    "holistic-education-beyond-academic-scores",
    "Holistic Education: Why Children Need More Than Academic Scores",
    "A simple guide for parents.",
    "Holistic Learning",
    "2026-08-11",
    "/images/article-15.jpg",
    ["holistic education", "academic scores", "parent guide"],
    [
      { kind: "lead", text: "Good marks matter: they show that a child has learned and performed well in a particular assessment. But a child's potential is bigger than a number. Education should help children think, question, reason, solve problems, communicate, adapt, make decisions and keep learning." },
      { kind: "heading", text: "What does holistic education mean?" },
      { kind: "paragraph", text: "Holistic education does not mean ignoring academics. It means recognising that academic knowledge is one important part of development—not the entire picture. Knowledge gives children a foundation, thinking skills help them use it, experiences help them apply it and feedback helps them grow." },
      { kind: "heading", text: "Six dimensions of a more complete learning journey" },
      { kind: "steps", items: [{ title: "Understanding", text: "Understand ideas rather than simply remember answers." }, { title: "Thinking", text: "Question, compare, connect and reason." }, { title: "Application", text: "Use knowledge in unfamiliar situations." }, { title: "Problem-solving", text: "Approach challenges and explore possible solutions." }, { title: "Curiosity", text: "Remain willing to ask, explore and discover." }, { title: "Growth", text: "Recognise strengths and areas for improvement." }] },
      { kind: "callout", tone: "note", title: "Holistic does not mean everything at once", text: "It does not mean more subjects, homework or examinations. It means a better balance between knowing, understanding, thinking, applying and growing." },
      { kind: "heading", text: "How the Epoch ecosystem supports holistic learning" },
      { kind: "paragraph", text: "Brainiac Global builds the thinking foundation for early learners. Epoch Olympiad assesses, challenges and explores subject learning for Classes 1–10. IHOST brings Mathematics, Science, Aptitude and General Knowledge together, while IFLY supports finance and digital literacy. MY CCBee makes daily learning visible, and the Academic Health Report helps families see beyond one score." },
      { kind: "quote", text: "Beyond marks. Beyond memorisation. Towards the whole child." },
      { kind: "faq", title: "Questions parents ask", items: [{ q: "Does holistic education mean academics are not important?", a: "No. Academic knowledge remains an important foundation; holistic education complements it with thinking, application and growth." }, { q: "Why are scores not enough?", a: "Scores show performance in an assessment but may not reveal reasoning, application, curiosity or how a child approaches unfamiliar problems." }, { q: "How can parents support holistic development?", a: "Encourage questions, conversations, problem-solving, exploration, reading, independent thinking and reflection." }] },
    ]
  ),
];
